# Generated by Django 4.2.7 on 2023-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='img'),
        ),
    ]
