# Generated by Django 4.2.6 on 2023-11-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price1')),
                ('price2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price2')),
            ],
        ),
    ]
