# Generated by Django 4.2.6 on 2023-11-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Homes'},
        ),
    ]
