# Generated by Django 4.2.6 on 2023-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='big_img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='img'),
        ),
    ]
