# Generated by Django 4.2.6 on 2023-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutus_alter_home_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
        ),
    ]
