# Generated by Django 4.2.7 on 2023-11-17 14:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.ImageField(null=True, upload_to='', verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='phone'),
        ),
    ]
