# Generated by Django 4.2.6 on 2023-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_furniture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='text',
        ),
        migrations.AddField(
            model_name='furniture',
            name='text1',
            field=models.TextField(null=True, verbose_name='text1'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='text2',
            field=models.TextField(null=True, verbose_name='text2'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='text3',
            field=models.TextField(null=True, verbose_name='text3'),
        ),
    ]
