# Generated by Django 4.2.6 on 2023-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_furniture_text_furniture_text1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='text3',
        ),
        migrations.AddField(
            model_name='furniture',
            name='text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
