# Generated by Django 4.2.6 on 2023-11-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_furniture_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='text',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='text2',
        ),
    ]
