# Generated by Django 4.2.6 on 2023-11-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
    ]
