# Generated by Django 4.2.6 on 2023-11-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='client name')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
                ('review', models.TextField(verbose_name='text')),
            ],
        ),
    ]
