# Generated by Django 4.2.7 on 2023-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Blog image')),
                ('title', models.CharField(max_length=150, verbose_name='Blog title')),
                ('text', models.TextField(verbose_name='About blog')),
                ('date', models.DateField(verbose_name='Post date')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
