# Generated by Django 4.2.7 on 2023-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='title')),
                ('text1', models.TextField(max_length=255, verbose_name='text1')),
                ('text2', models.TextField(max_length=255, verbose_name='text2')),
            ],
        ),
    ]
