# Generated by Django 4.2.7 on 2023-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='img_open',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Drop down image'),
        ),
    ]
