# Generated by Django 4.2.7 on 2023-11-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
    ]
