# Generated by Django 4.2.7 on 2023-11-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contactus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='text',
        ),
    ]
